DEMO_STORE_SETTINGS = {
    "phone": "+56 2 2345 6789",
    "schedule": "Lun – Vie 9:00 – 18:00 hrs",
    "support_label": "Atención al cliente",
    "support_href": "/help",
    "contact_email": "contacto@binfrix.com",
    "store_url": "http://localhost:5174",
    "store_logo_url": "",
    "storefront_template": "sports",
    "multilingual_enabled": False,
    "default_locale": "es",
    "account_label": "Cuenta",
    "account_href": "/account",
    "promo_messages": [
        "Compra con hasta 6 cuotas sin interés",
        "Servicio técnico propio",
        "30 días para cambios y devoluciones",
    ],
    "header_links": [
        {"label": "Servicio al cliente", "href": "/help", "group": "left"},
        {"label": "Tiendas", "href": "/about/corporate-site", "group": "left"},
        {"label": "Recetas", "href": "/help", "group": "left"},
    ],
    "social_links": [
        {
            "id": "instagram",
            "label": "Instagram",
            "href": "https://instagram.com",
            "show_in_header": True,
            "show_in_footer": True,
        },
        {
            "id": "x",
            "label": "X",
            "href": "https://x.com",
            "show_in_header": True,
            "show_in_footer": True,
        },
        {
            "id": "facebook",
            "label": "Facebook",
            "href": "https://facebook.com",
            "show_in_header": True,
            "show_in_footer": True,
        },
        {
            "id": "youtube",
            "label": "YouTube",
            "href": "https://youtube.com",
            "show_in_header": True,
            "show_in_footer": False,
        },
    ],
}
